##
# Copyright (C) 2024-2026 Charles Y. Choi
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

SRC_DIR=.

.PHONY: tests
tests: casual-avy-tests

.PHONY: casual-avy-tests
casual-avy-tests:
	$(MAKE) -C $(SRC_DIR) -f Makefile-casual-avy.make tests

.PHONY: package-lint
package-lint:
	$(MAKE) -C $(SRC_DIR) -f Makefile-casual-avy.make $@

.PHONY: regression
regression:
	$(MAKE) -C $(SRC_DIR) -f Makefile-casual-avy.make $@

.PHONY: clean
clean:
	$(MAKE) -C $(SRC_DIR) -f Makefile-casual-avy.make $@
